### ISSUE TITLE
Create a mono build configuration

### ISSUE THREAD

**Issue by kristjank** [kristjank/ark-net#8]

**Comment by sharkdev-j** [comment]
Instead of making a mono build we should migrate the project to use .NET Standard. I believe they are on version 1.6. Xamarin has integration with .NET Standard and is the go to framework for mobile cross platform development.  The lib we be usable in a xamarin solution if the project is .NET Standard

**Comment by sharkdev-j** [comment]
I have a few years experience working with xamarin and PCLs but the .NET Standard seems to be the next best solution and I think we should use it

**Comment by kristjank** [comment]
Hi - 
sure, this is the goal, we can go this way after we close the next release with the fixes we are working on. It would be great to switch to .NET Standard I agree. (have it on my todo list for quite a while)...

**Comment by sharkdev-j** [comment]
Awesome!  Sounds like a plan.  Hopefully the other 3rd party libs we are using support .NET Standard .  Not sure about NBitcoin.  We also should remove libs we are not using anymore (if there are any).
